import {
  MonitorSmartphone,
  Server,
  Database,
  Smartphone,
  GitBranch,
  BrainCircuit,
  Code2,
  AppWindow,
  Sparkles,
  GraduationCap,
  HeartPulse,
  ShoppingCart,
  Landmark,
  Building2,
  Truck,
  Rocket,
  Store,
  Target,
  Gauge,
  TrendingUp,
  Cpu,
  MessagesSquare,
  LifeBuoy,
  Layers,
  Braces,
  Globe,
  BarChart3,
  Circle,
  Clock,
  ArrowRight,
  ArrowUpRight,
  ChevronRight,
  Check,
  CheckCircle2,
  Phone,
  Mail,
  ExternalLink,
  Shield,
} from "lucide-react";

const iconMap = {
  MonitorSmartphone,
  Server,
  Database,
  Smartphone,
  GitBranch,
  BrainCircuit,
  Code2,
  AppWindow,
  Sparkles,
  GraduationCap,
  HeartPulse,
  ShoppingCart,
  Landmark,
  Building2,
  Truck,
  Rocket,
  Store,
  Target,
  Gauge,
  TrendingUp,
  Cpu,
  MessagesSquare,
  LifeBuoy,
  Layers,
  Braces,
  Globe,
  BarChart3,
  Circle,
  Clock,
  ArrowRight,
  ArrowUpRight,
  ChevronRight,
  Check,
  CheckCircle2,
  Phone,
  Mail,
  ExternalLink,
  Shield,
};

// Central icon resolver so data files can reference icons by string name
export default function Icon({ name, className = "h-5 w-5", ...props }) {
  const LucideIcon = iconMap[name] || ArrowRight;
  return <LucideIcon className={className} aria-hidden="true" {...props} />;
}
